config/routes.rb
Timeclock::Application.routes.draw do

  resources :employees do
    resources :timesheets do
      get 'current'
      get 'show'
      post 'update'

    end
  end

  root :to => redirect('/login')
  get 'employees/:eid/payperiods/:pid' => 'timesheets#select'
  get 'massexport/payperiods/:pid' => 'timesheets#massExport'
  get 'login' =>'sessions#new'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get  'logout' => 'sessions#logout'
  get 'auth/failure'=> 'sessions#failure'

  get 'employees/main/:id' => 'employees#main'

  post 'employees/clockin/:clockingin' => 'employees#clockin'

  get  'fakelogin/:uid' => 'sessions#fakelogin' #this is for capybara testing purposes and should be deleted upon deployment

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  after_initialize :init


  validates :name, :presence =>true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :email, :presence =>true
  validates :email, :uniqueness => true

  #The four lines below setup the relationship between employees and supervisors
  has_many   :ownerships, :class_name => "Supervisor" , :foreign_key => "supervisor_id"
  has_many   :employees,  :through => :ownerships, :source => :employee
  has_one    :owner     , :class_name => "Supervisor" , :foreign_key => "employee_id"
  has_one    :supervisor, :through => :owner, :source => :supervisor
  #-----------------------------------------------------------

  has_many   :timesheets


  def clockin?
    #debugger
    self.timesheets.current[0].clockin?
  end

  def self.create_on_first_login(auth)
    @employee = Employee.find_by_email(auth['info']['email'])
    if (@employee)
      @employee.uid= auth['uid']
      @employee.save!
      return @employee
    else
      return nil
    end
  end

  def clock_in(clockin)
    if clockin == "true"
      self.timesheets.current[0].days.current[0].in_and_outs.create!(:in_time => DateTime.now())
    elsif clockin == "false"
      inandout = self.timesheets.current[0].days.current[0].in_and_outs.find_dangling_in[0]
      inandout.out_time = DateTime.now() if inandout
      inandout.save! if inandout
    end
  end

  def init
    self.admin ||= false
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :logged_in?
  before_action :admin_user,      only: [:edit,:update,:show,:index,:new,:create,:destroy,:edit]

  # POST create
  def create
    @employee = Employee.new(employee_params) ##Invoke user_params methods
    if @employee.save
      flash[:notice] = "#{@employee.name} was successfully added."
      redirect_to employees_path
    else
      render 'new'
    end
  end

  def clockin
    clockin = params[:clockingin]
    @employee = Employee.find_by_uid(session[:user_uid])
    @employee.clock_in(clockin)
    render(:partial => 'clockinout') if request.xhr?
  end

  # GET #index
  def index
    @employees = Employee.all
    @payperiods = Payperiod.all_cache
  end

  # GET #show
  def show
    id = params[:id]
    @employee = Employee.find(id)

    if (@employee.id == @current_user.id || @current_user.admin)
    else
      redirect_to  "/employees/#{@employee.id}/timesheets/1/current"
    end
  end

  # GET #new
  def new
    @employee = Employee.new
    #AdminMailer.admin_email(@current_user).deliver_now
  end

  # GET #edit
  def edit
      @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find params[:id]
    if @employee.update_attributes(employee_params)
      flash[:notice] = "#{@employee.name} was successfully updated."
      redirect_to employee_timesheet_current_path(@employee , timesheet_id: 1)
    else
      render 'edit'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.uid != @current_user.uid
      flash[:notice] = "Employee '#{@employee.name}' was deleted."
      @employee.destroy
    else
      flash[:notice] = "You tried to delete yourself."
    end
    redirect_to employees_path
  end

  private

  ## Strong Parameters
  def employee_params
    params.require(:employee).permit(:name ,:email)
  end

  def admin_user
    redirect_to  "/employees/#{@current_user.id}/timesheets/1/current" unless @current_user.admin?
  end

  def logged_in?
    redirect_to '/login' if @current_user.nil?
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def employee_main_path(employee)
    "/employees/main/" + employee.id
  end
end

app/views/employees/_employee.html.haml
-#A single row of the All Employees table
%tr
  %td= link_to "#{employee.name}", employee_timesheet_current_path(employee , timesheet_id: 1)
  %td= employee.email

app/views/employees/_employee_form.html.haml
-#This is a partial to be used when ever an employee form is needed
- unless @employee.errors.empty?
  #warning
    Errors prevented this employee from being #{controller.action_name}d
    %ul
      - @employee.errors.full_messages.each do |error|
        %li=  error
%p
  = label :employee , :name, 'Name:'
  = text_field :employee, :name
%p
  = label :employee , :email, "Email:"
  = text_field :employee, :email
%br
%br

app/views/employees/edit.html.haml
%div#headerbar
  %h2 Edit Employee Information
%div.content
  = form_tag employee_path(@employee), :method => :put do
    = render :partial => 'employee_form'
    = submit_tag 'Save Changes'

app/views/employees/index.html.haml
%div#contentheader  
  %div.menubar
    %div
      %a= render :partial => '/sessions/logout'
      = link_to 'Add a new employee', new_employee_path, class: "button menu"
  %div#headerbar
    %h1 All Employees
%div.content
  %div.container.third
    %select{:name => "name_select", :id => "nameSelector"}
      %option{:value => "All"} All
      -@employees.each do |e|
        -if not e.admin
          %option{:value => e.id} #{e.name}
    %select{:name => "period_select", :id => "periodSelector"}
      -@payperiods.reverse_each do |p|
        %option{:value => p.id} #{p.print}
    %button{:id => "export", :onclick => "Employees.massExport()"} Export Timesheets
  %div.container.two-thirds
    %table.vblu.employees#index
      %thead
        %tr
          %th Name
          %th Email
      %tbody
        = render :partial => 'employee' , :collection=>@employees

app/views/employees/main.html.haml
%h1 Health 4 All
%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"}
%br
%button{:id => "checkin"} Check In
%button{:id => "checkout"} Check Out

%h2 Hours for current pay period:

app/views/employees/new.html.haml
%div#headerbar
  %h2 Add new Employee
%div.content
  = form_tag employees_path, :method => :post do

    = render :partial => 'employee_form'
    = submit_tag 'Save Changes'

app/views/employees/show.html.haml
%div#headerbar
  %h1 #{@employee.name}
%div.menubar
  %div
    %a= render :partial => '/sessions/logout'
    = link_to 'Back to employee list' , employees_path, :class => "button menu"
%div.content
  %div#details

    %strong Email:
    = @employee.email
    %br
    %br
    -if !@employee.admin
      = link_to "View employee's current timesheets" , employee_timesheet_current_path(@employee , timesheet_id: 1)
      %br
      %br
    = link_to "Edit info" , edit_employee_path(@employee)
    %br
    %br

    = link_to "Delete" , employee_path(@employee) , :method => :delete