config/routes.rb
Timeclock::Application.routes.draw do

  resources :employees do
    resources :timesheets do
      get 'current'
      get 'show'
      post 'update'

    end
  end

  root :to => redirect('/login')
  get 'employees/:eid/payperiods/:pid' => 'timesheets#select'
  get 'massexport/payperiods/:pid' => 'timesheets#massExport'
  get 'login' =>'sessions#new'
  get 'auth/:provider/callback' => 'sessions#create'
  post 'logout' => 'sessions#destroy'
  get  'logout' => 'sessions#logout'
  get 'auth/failure'=> 'sessions#failure'

  get 'employees/main/:id' => 'employees#main'

  post 'employees/clockin/:clockingin' => 'employees#clockin'

  get  'fakelogin/:uid' => 'sessions#fakelogin' #this is for capybara testing purposes and should be deleted upon deployment

end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :payperiod
  has_many   :days

  after_initialize :init
  after_create    { |t| t.make_days (false) }
  scope :current, lambda {
      date = Date.today()
      payperiod = Payperiod.find_payperiod(date)
      timesheets = Timesheet.where("payperiod_id = :id" , :id => payperiod.id).includes(:days)
   }


  def totalHours
    value = 0.00
    days.each do |day|
      day.in_and_outs.each do |shift|
        if (shift.in_time and shift.out_time)
          diff = Time.diff(shift.out_time , shift.in_time)
          value += diff[:hour]
          value += (diff[:minute] / 60.00)
        end
      end
    end
    return value.round(2)
  end

  def clockin?
    #iN = false
    #self.days.each do |day|
    #  iN ||= day.clockin?
    #end
    return self.days.current[0].clockin?
  end

  def init
    #If a timesheet is created without a payperiod assume it is for the current period
    self.payperiod ||= Payperiod.find_payperiod(Date.today())
  end

  def make_days( build )
    #Create all the days of a timesheet if they don't exist yet
    if (!self.days.blank?)
      return
    end
    payperiod  = self.payperiod
    start_date = payperiod.start_date
    end_date   = payperiod.end_date
    dates = (start_date.to_date..(end_date )).map{ |date| date}
    dates.each do |day|
      self.days.build(day: day) if build
      self.days.create(day: day ) unless build
    end
  end

  def halves
    i = -1
    length = self.days.length
    self.days.partition { i += 1; i< length / 2}
  end

  def self.verifyAndCreate( days, employee , payperiod)
    @timesheet = employee.timesheets.build(  :payperiod=> payperiod)
    @timesheet.make_days(true)
    days = days["days"]
    days.each_with_index  do | day , i|
      inandouts = day[1]
      inandouts.each do |inandout|
        day = @timesheet.days[i]
        inandout['in'] = DateTime.parse( day.day.to_s + " " + inandout['in']) + 5.hours unless inandout['in'] == ''
        inandout['out'] = DateTime.parse( day.day.to_s + " " + inandout['out']) + 5.hours unless inandout['out'] == ''
        inandout['out'] = nil if inandout['out'] == ''
        @timesheet.days[i].in_and_outs.build( :in_time => inandout['in'] , :out_time => inandout['out'])
      end
    end
    return @timesheet
  end


end

app/controllers/timesheets_controller.rb
require 'json'
require 'zip'

class TimesheetsController < ApplicationController
  def show
    @current = false
    @employee  = Employee.find_by_id(params[:employee_id])
    @payperiods = Payperiod.all_cache
    @timesheet = Timesheet.find_by_id(params[:timesheet_id])
    @payperiod = @timesheet.payperiod
    if( Payperiod.find_payperiod(Date.today()) == @payperiod )
      @current = true
    end
    @start_date = @payperiod.start_date
    @end_date   = @payperiod.end_date
    halves = @timesheet.halves
    @first_week  = halves[0]
    @second_week = halves[1]
    @name = @employee.name
    @uid  = @employee.uid
    @total_hours = @timesheet.totalHours
    respond_to do |format|
      format.html
      format.xls { headers["Content-Disposition"] = "attachment; filename=\"timesheet_" + @employee.name + "_" + @payperiod.file_print + ".xls\"" }
    end
  end

  def current
    @employee  = Employee.find_by_id(params[:employee_id])
    @timesheet = @employee.timesheets.current[0]
    if(!@timesheet)
      @timesheet = @employee.timesheets.create!()
    end
    respond_to do |format|
      format.html { redirect_to  employee_timesheet_show_path(@employee, @timesheet) }
      format.xls  { redirect_to  employee_timesheet_show_path(@employee, @timesheet, format: "xls") }
    end
  end

  def update
    @payperiod = Payperiod.find_payperiod(Date.today)
    @employee  = Employee.find_by_uid(session[:user_uid])
    @timesheet = Timesheet.find_by_id(params[:timesheet_id])
    @newtimesheet = ActiveSupport::JSON.decode(request.body.read) #This resort is needed
    @newtimesheet = Timesheet.verifyAndCreate(@newtimesheet , @employee , @payperiod)
    if( @timesheet)

      @timesheet.days = @newtimesheet.days
      @timesheet.save!
      render :partial => 'goodedit'
    else
      render(:partial => 'badedit')
    end
  end

  def select
    @employee = Employee.find_by_id(params[:eid])
    payperiod = Payperiod.find_by_id(params[:pid])
    @timesheet = @employee.timesheets.where("payperiod_id = ?", payperiod)[0]
    if(!@timesheet)
      @timesheet = @employee.timesheets.create!(payperiod: payperiod)
    end
    respond_to do |format|
      format.html { redirect_to  employee_timesheet_show_path(@employee, @timesheet) }
      format.xls  { redirect_to  employee_timesheet_show_path(@employee, @timesheet, format: "xls") }
    end
  end

  def massExport
    employees = Employee.all
    payperiod = Payperiod.find_by_id(params[:pid])
    zip_name = "timesheets_" + payperiod.file_print + ".zip"
    File.delete("./tmp/#{zip_name}") unless not File.exist?("./tmp/#{zip_name}")
    Zip::File.open("./tmp/#{zip_name}", Zip::File::CREATE) do |zipfile|
      employees.each_with_index do |e , i|
        if e.admin
          next
        end
        @employee = e
        @timesheet = Timesheet.where("payperiod_id = ? AND employee_id = ?", payperiod.id, @employee.id)[0]
        if(!@timesheet)
          @timesheet = @employee.timesheets.create!(payperiod: payperiod)
        end
        data = render_to_string "show.xls"
        filePath = "timesheet_" + @employee.name + "_" + payperiod.file_print + ".xls"
        #tf = Tempfile.new([filePath , ".xls"])
        tf = File.open("#{Rails.root}/tmp/myfile_#{filePath}",'w')
        tf << data
        puts filePath
        puts tf.path
        #zf.put_next_entry(filePath)
        #zf.print IO.read(tf.pat
        print filePath
        zipfile.add(filePath , tf.path) if filePath.present?
        tf.close
      end
    end
    #zip = Tempfile.new(zip_name)
    #Zip::OutputStream.open(zip) do |zf|
    #  employees.each do |e|
    #    if e.admin
    #      next
    #    end
    #    @employee = e
    #    @timesheet = Timesheet.where("payperiod_id = ? AND employee_id = ?", payperiod.id, @employee.id)[0]
    #    if(!@timesheet)
    #      @timesheet = @employee.timesheets.create!(payperiod: payperiod)
    #    end
    #    data = render_to_string "show.xls"
    #    filePath = "timesheet_" + @employee.name + "_" + payperiod.file_print + ".xls"
    #    tf = Tempfile.new(filePath)
    #    tf << data
    #    tf.close
    #    zf.put_next_entry(filePath)
    #    zf.print IO.read(tf.path)
    #  end
    #end
    #zip_data = File.read(zip.path)
    #send_data zip_data, :type => "application/zip", :filename => zip_name
    #zip.close
    #File.delete("#{Rails.root}/tmp/#{zip_name}"
    send_file "./tmp/#{zip_name}", :type => 'application/zip', :filename => "#{zip_name}"
    #File.delete("./tmp/#{zip_name}")
  end

end


#def get_stream(contractors)
#  begin
##    Zip::File.open("#{Rails.root}/tmp/zipfile_name.zip", Zip::File::CREATE) do |zipfile|
 #     contractors.each_with_index do |filename, index|
  #      zipfile.add(filename.try(:cv_file_name), filename.try(:cv).try(:path)) if filename.present?
   #   end
   # end

    #send_file "#{Rails.root}/tmp/zipfile_name.zip", :type => 'application/zip', :filename => "Contractor_cvs.zip", :x_sendfile => true
    #File.delete("#{Rails.root}/tmp/zipfile_name.zip")

#  rescue
 # end
#end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/timesheets/_rmenu.html.haml
%div.hide#rmenu
  %div#rowcontainer
  %ul
    %li
      %div{onclick: "alert(1);"}Delete
    %li
      %div{onclick: "alert(1);"}Insert Entry Above
    %li
      %div{onclick: "alert(1);"}Insert Entry Below

app/views/timesheets/_timesheet.html.haml
%div
  %div.half
    %h3 #{first_week.first.day.strftime("%B %d - ") + first_week.last.day.strftime("%d, %Y")}
    = render :partial => "timesheet_table", :locals => {:days => first_week , :start => 1 }
  %div.half
    %h3 #{second_week.first.day.strftime("%B %d - ") + second_week.last.day.strftime("%d, %Y")}
    = render :partial => "timesheet_table", :locals => {:days => second_week ,:start => middle }

app/views/timesheets/_timesheet_table.html.haml
-#The represenation of a timesheet as a table
- count = start
- days.each do |day|
  - day.num = count
  - count = count + 1
%table.vblu
  %thead
    %tr
      %th Date
      %th In
      %th Out
  %tbody
    = render :partial => '/days/day'  ,:collection=>days

app/views/timesheets/show.html.haml
%div#clockinquestionmark{ :style => "display :none"}= @employee.clockin?
%div#contentheader  
  %div.menubar
    %a= render :partial => '/sessions/logout'
    -if @current_user.admin 
      = link_to 'Back to employee list' , employees_path, :class => "button menu"
    -if @uid == session[:user_uid] || @current_user.admin
      -if @current_user
        = link_to 'Export Timesheet', employee_timesheet_show_path(@employee, @timesheet, format: "xls"), :class => "button menu"
  %div#headerbar
    %h1.font Payperiod for
    %h1 #{@name}
%div.content
  %div.container.third
    %select{:name => 'pay_pariod', :id => "periodSelector", :onchange => "TimeSheet.changePeriod()"}
      -@payperiods.reverse_each do |p|
        -if p.start_date == @start_date
          %option{:value => p.id, :selected => "selected"} #{p.print}
        -else
          %option{:value => p.id} #{p.print}
    -if @uid == session[:user_uid] || @current_user.admin
      -if @current
        -if @uid == session[:user_uid]
          %button.button{:id => "clockin"} Clock In
        %button{:id => "submit", :style => "display: none"} Submit Changes
        %button{:id => "revert", :style => "display: none"} Revert Changes
    -if @current_user.admin 
      %p
        %strong Name:
        = @employee.name
      %p
        %strong Email:
        = @employee.email
      %p= link_to "Edit info" , edit_employee_path(@employee)
      %p= link_to "Delete" , employee_path(@employee) , :method => :delete
  %div.container.two-thirds
    = render :partial => "timesheet" , :locals => { :first_week => @first_week , :second_week => @second_week , :middle => (@timesheet.days.length/2)+1 }
    %p.right Total: #{@total_hours} hours

app/views/timesheets/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="Dates">
      <Interior ss:Color="#E9E9E9" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="Headers">
      <Interior ss:Color="#BDBDBD" ss:Pattern="Solid"/>
    </Style>
    <Style ss:ID="Info">
      <Interior ss:Color="#E9E9E9" ss:Pattern="Solid"/>
    </Style>
  </Styles>
  <Worksheet ss:Name="Sheet1">
    <Table>
      <ss:Column ss:width="100"/>
      <ss:Column ss:width="100"/>
      <ss:Column ss:width="100"/>
      <Row>
        <Cell ss:StyleID="Info"><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String"><%= @employee.name %></Data></Cell>
      </Row>
      <Row>
        <Cell ss:StyleID="Info"><Data ss:Type="String">Pay Period</Data></Cell>
        <Cell><Data ss:Type="String"><%= @timesheet.payperiod.print %></Data></Cell>
      </Row>
      <Row>
        <Cell ss:StyleID="Headers"><Data ss:Type="String">Date</Data></Cell>
        <Cell ss:StyleID="Headers"><Data ss:Type="String">In</Data></Cell>
        <Cell ss:StyleID="Headers"><Data ss:Type="String">Out</Data></Cell>
        <Cell ss:StyleID="Headers"><Data ss:Type="String">Hours</Data></Cell>
      </Row>
      <% @timesheet.days.each do |day| %>
      <Row>
        <Cell ss:StyleID="Dates"><Data ss:Type="String"><%= day.print %></Data></Cell>
      <% if not day.in_and_outs.empty? %>
      <% day.in_and_outs.each_with_index do |inandout, index| %>
      <% if index == 0 %>
        <Cell><Data ss:Type="String"><%= (inandout.in_time - 5.hours).strftime("%H:%M") %></Data></Cell>
        <% if inandout.out_time %>
        <Cell><Data ss:Type="String"><%= (inandout.out_time - 5.hours).strftime("%H:%M") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ((inandout.out_time.to_time - inandout.in_time.to_time)/1.hour).round(2) %></Data></Cell>
        <% end %>
      </Row>
      <% else %>
      <Row>
        <Cell ss:StyleID="Dates"><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= (inandout.in_time - 5.hours).strftime("%H:%M") %></Data></Cell>
        <% if inandout.out_time %>
        <Cell><Data ss:Type="String"><%= (inandout.out_time - 5.hours).strftime("%H:%M") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= ((inandout.out_time.to_time - inandout.in_time.to_time)/1.hour).round(2) %></Data></Cell>
        <% end %>
      </Row>
      <% end %>
      <% end %>
      <% else %>
      </Row>
      <% end %>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>